version: "3.8"
services:
  mongo1:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: password1
      MONGO_INITDB_DATABASE: db1
    ports:
      - "27017:27017"